"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Import para el LLM
import os
import secrets

from dotenv import load_dotenv

# Cargar .env desde la raíz del proyecto (el directorio que contiene manage.py).
# Necesario para que SECRET_KEY esté disponible cuando Django arranca vía
# wsgi/asgi sin pasar por manage.py (que ya tiene su propio load_dotenv).
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Si SECRET_KEY no está en .env se genera una clave aleatoria de sesión.
# ⚠ Esto invalida sesiones activas en cada reinicio; define SECRET_KEY en .env.
_secret_from_env = os.getenv("SECRET_KEY", "")
SECRET_KEY = _secret_from_env if _secret_from_env else secrets.token_hex(50)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.getenv('DEBUG', 'False') == 'True'



# No vacio, asi si cambiamos DEBUG = False para el despliegue, seguira funcionando en local.
# El ultimo para metricas de n8n
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '172.18.0.1']
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,172.18.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'WebBuilder',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
	
	'django.contrib.humanize',
    'encrypted_model_fields',
]

#MIDDLEWARE = [
#    'django.middleware.security.SecurityMiddleware',
#    'django.contrib.sessions.middleware.SessionMiddleware',
#	'django.middleware.locale.LocaleMiddleware',
#    'django.middleware.common.CommonMiddleware',
#    'django.middleware.csrf.CsrfViewMiddleware',
#    'django.contrib.auth.middleware.AuthenticationMiddleware',
#    'django.contrib.messages.middleware.MessageMiddleware',
#    'django.middleware.clickjacking.XFrameOptionsMiddleware',
#]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["templates", ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'webbuilder_db'),
        'USER': os.getenv('DB_USER', 'webbuilder_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Español'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Directo al login si no esta logueado
LOGIN_URL = 'login'
# Vuelta al home si no tiene next page
LOGIN_REDIRECT_URL = 'home'
# Manda al login tras un logout
LOGOUT_REDIRECT_URL = 'login'

# ── Sesiones ──────────────────────────────────────────────────────────────────
# Nombre de cookie único para evitar conflictos si se accede mezclando
# localhost y 127.0.0.1 (cookies distintas por host aunque mismo puerto).
SESSION_COOKIE_NAME = 'webbuilder_sessionid'
# Las sesiones persisten aunque se cierre el navegador (hasta expiración).
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# 2 semanas de vida de sesión (en segundos).
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14

# LLM
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "https://openrouter.ai/api/v1")
LLM_API_KEY = os.getenv("LLM_API_KEY", "")
LLM_MODEL = os.getenv("LLM_MODEL", "meta-llama/llama-3.3-70b-instruct:free")

# n8n deploy
N8N_DEPLOY_WEBHOOK = os.getenv("N8N_DEPLOY_WEBHOOK", "http://localhost:5678/webhook/webbuilder-deploy")
N8N_LOCAL_FILES_PATH = os.getenv("N8N_LOCAL_FILES_PATH", "/home/alejandro/Desktop/TFG/docker/n8n/local-files")

# n8n login
N8N_WEBHOOK_REGISTRO = os.getenv("N8N_WEBHOOK_REGISTRO", "http://localhost:5678/webhook/WebBuilder-Register")
N8N_WEBHOOK_LOGIN    = os.getenv("N8N_WEBHOOK_LOGIN",    "http://localhost:5678/webhook/WebBuilder-Login")

# n8n generation
N8N_WEBHOOK_GENERATION_DONE = os.environ.get("N8N_WEBHOOK_GENERATION_DONE", "http://localhost:5678/webhook/webbuilder-generation-done")

# n8n daily metrics
INTERNAL_TOKEN = os.environ.get("INTERNAL_TOKEN", "")

# Logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# LLM personalizados
FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY", "")

# Despligue Railway
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')