# Generated by Django 5.1.7 on 2025-07-19 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(verbose_name='URL de la API')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('source_data', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesada'), ('error', 'Error')], default='pending', max_length=20)),
                ('response_summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
