# Generated by Django 5.2.6 on 2026-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequest',
            old_name='source_data',
            new_name='error_message',
        ),
        migrations.AddField(
            model_name='apirequest',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='raw_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
