# Generated by Django 5.2.6 on 2026-02-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0002_rename_source_data_apirequest_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='field_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
