# Generated by Django 5.2.6 on 2026-02-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0003_apirequest_field_mapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequest',
            old_name='raw_response',
            new_name='raw_data',
        ),
    ]
