# Generated by Django 5.2.6 on 2026-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0004_rename_raw_response_apirequest_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='plan_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
