# Generated by Django 5.2.6 on 2026-02-23 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0005_apirequest_plan_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plublic_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accepted_plan', models.JSONField()),
                ('theme_templates', models.JSONField(blank=True, default=dict)),
                ('theme_css', models.TextField(blank=True, default='')),
                ('theme_prompt', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='WebBuilder.apirequest')),
            ],
        ),
    ]
