# Generated by Django 5.2.6 on 2026-02-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0006_generatedsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedsite',
            old_name='plublic_id',
            new_name='public_id',
        ),
    ]
