# Generated by Django 5.2.6 on 2026-03-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0007_rename_plublic_id_generatedsite_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedsite',
            old_name='theme_css',
            new_name='generation_error',
        ),
        migrations.RenameField(
            model_name='generatedsite',
            old_name='theme_templates',
            new_name='project_files',
        ),
        migrations.RemoveField(
            model_name='generatedsite',
            name='theme_prompt',
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('generating', 'Generando'), ('ready', 'Listo'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='project_name',
            field=models.SlugField(blank=True, default='', max_length=80),
        ),
    ]
