# Generated by Django 5.2.6 on 2026-03-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0008_rename_theme_css_generatedsite_generation_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsite',
            name='deploy_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='deploy_status',
            field=models.CharField(choices=[('idle', 'Sin desplegar'), ('deploying', 'Desplegando'), ('done', 'Desplegado'), ('error', 'Error')], default='idle', max_length=30),
        ),
    ]
