# Generated by Django 5.2.6 on 2026-03-23 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0009_generatedsite_deploy_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=50)),
                ('llm_model', models.CharField(max_length=100)),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
                ('consistency_errors', models.JSONField(default=list)),
                ('had_retry', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_logs', to='WebBuilder.generatedsite')),
            ],
        ),
    ]
