# Generated by Django 5.2.6 on 2026-03-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0010_generationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='input_type',
            field=models.CharField(choices=[('url', 'URL'), ('file', 'Fichero')], default='url', max_length=10),
        ),
    ]
