# Generated by Django 5.2.6 on 2026-04-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0011_apirequest_input_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('project_files', models.JSONField(default=dict)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='WebBuilder.generatedsite')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
