# Generated by Django 5.2.6 on 2026-04-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0012_siteversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('super', 'Superusuario'), ('normal', 'Usuario normal')], default='normal', max_length=10)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_users', to='WebBuilder.generatedsite')),
            ],
            options={
                'unique_together': {('site', 'username')},
            },
        ),
    ]
