# Generated by Django 5.2.6 on 2026-04-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedsite',
            name='generation_step',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
