# Generated by Django 5.2.6 on 2026-05-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebBuilder', '0015_generatedsite_generation_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'English')], default='en', max_length=10),
        ),
    ]
